### ISSUE TITLE
Create a catch all for routes that don't exist

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/news-from-the-wormhole#22]
If a user tries to route to a route that doesn't exist, we should either route them to home, or create a View that tells them that route doesn't exist.

**Comment by RodrigoRVSN** [comment]
we already have this catch, no?

![image](https://user-images.githubusercontent.com/75763403/193428933-72090486-42d9-4a19-9abb-71fa44a236c9.png)

**Comment by JasonFritsche** [comment]
Closed in a previous PR
