### ISSUE TITLE
Show a loader when the infinite scroll is loading more articles

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/news-from-the-wormhole#23]
It's not clear that more articles are being loader, maybe we can show a loader at the bottom of the articles when more articles are being fetched.

**Comment by Ujjawal3** [comment]
Hi @JasonFritsche can I work on this as part of hacktoberfest?

**Comment by JasonFritsche** [comment]
@Ujjawal3 you can absolutely work on this!
