### ISSUE TITLE
Make particles disappear on hover

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/news-from-the-wormhole#48]
I think it would be cool to make the particles disappear when a user hovers over them like in [this NASA demo](https://vincentgarreau.com/particles.js/#nasa). This project uses react-tsparticles. The `options.tsx` file will need to be updated.

**Comment by Green-Ranger11** [comment]
This sounds fun! Could I please be assigned this?

**Comment by JasonFritsche** [comment]
@Green-Ranger11 all yours!
