### ISSUE TITLE
Fix Typing Issue in FetchArticles file

### ISSUE THREAD

**Issue by JasonFritsche** [JasonFritsche/news-from-the-wormhole#56]
The build is currently failing due to typing issues in `FetchArticles.tsx`.

**Comment by Frey0-0** [comment]
Please assign this issue to me. I would like to work on it.

**Comment by JasonFritsche** [comment]
@Frey0-0 all yours!

**Comment by Frey0-0** [comment]
@JasonFritsche `npm run dev` is working perfectly on my local machine and I also didn't find any typin issues in the mentioned file. Although my IDE is just displaying some problems like the property success and articles don't exist on data which I can't understand but still the build is working perfectly. I can't understand what changes should I make :/

**Comment by JasonFritsche** [comment]
@Frey0-0 please make sure that you've got the latest code from the main branch. Afterwards, run `npm run build`.

**Comment by Green-Ranger11** [comment]
Is this still being worked on? If not, I'd like to give this a crack

**Comment by Green-Ranger11** [comment]
@JasonFritsche I've a PR in #58 if you would like to take a look a this at your earliest convenience. Thanks
